"""
Move validator for the chess engine.
Filters pseudo-legal moves to only legal moves (no self-check).
Provides check, checkmate, and stalemate detection.
"""
from engine.move_generator import MoveGenerator, Move


class MoveValidator:
    """Validates chess moves and detects check/checkmate/stalemate."""

    def __init__(self):
        self.move_generator = MoveGenerator()

    def is_square_attacked(self, board, row: int, col: int, by_color: str) -> bool:
        """Check if a square is attacked by any piece of the given color.

        Instead of generating all moves (expensive), we check directly
        from the target square whether any enemy piece can reach it.
        """
        enemy = by_color

        # Check for pawn attacks
        if enemy == 'w':
            # White pawns attack diagonally upward (from higher row to lower row)
            pawn_attack_row = row + 1  # white pawn would be one row below
            for dc in [-1, 1]:
                pc = col + dc
                if 0 <= pawn_attack_row < 8 and 0 <= pc < 8:
                    piece = board.get_piece(pawn_attack_row, pc)
                    if piece == 'wP':
                        return True
        else:
            # Black pawns attack diagonally downward (from lower row to higher row)
            pawn_attack_row = row - 1  # black pawn would be one row above
            for dc in [-1, 1]:
                pc = col + dc
                if 0 <= pawn_attack_row < 8 and 0 <= pc < 8:
                    piece = board.get_piece(pawn_attack_row, pc)
                    if piece == 'bP':
                        return True

        # Check for knight attacks
        knight_offsets = [
            (-2, -1), (-2, 1), (-1, -2), (-1, 2),
            (1, -2), (1, 2), (2, -1), (2, 1),
        ]
        for dr, dc in knight_offsets:
            nr, nc = row + dr, col + dc
            if 0 <= nr < 8 and 0 <= nc < 8:
                piece = board.get_piece(nr, nc)
                if piece == enemy + 'N':
                    return True

        # Check for king attacks (adjacent squares)
        for dr in [-1, 0, 1]:
            for dc in [-1, 0, 1]:
                if dr == 0 and dc == 0:
                    continue
                nr, nc = row + dr, col + dc
                if 0 <= nr < 8 and 0 <= nc < 8:
                    piece = board.get_piece(nr, nc)
                    if piece == enemy + 'K':
                        return True

        # Check for sliding piece attacks (bishop/queen on diagonals)
        for dr, dc in [(-1, -1), (-1, 1), (1, -1), (1, 1)]:
            nr, nc = row + dr, col + dc
            while 0 <= nr < 8 and 0 <= nc < 8:
                piece = board.get_piece(nr, nc)
                if piece is not None:
                    if piece[0] == enemy and piece[1] in ('B', 'Q'):
                        return True
                    break  # blocked by a piece
                nr += dr
                nc += dc

        # Check for sliding piece attacks (rook/queen on straights)
        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
            nr, nc = row + dr, col + dc
            while 0 <= nr < 8 and 0 <= nc < 8:
                piece = board.get_piece(nr, nc)
                if piece is not None:
                    if piece[0] == enemy and piece[1] in ('R', 'Q'):
                        return True
                    break
                nr += dr
                nc += dc

        return False

    def is_in_check(self, board, color: str) -> bool:
        """Check if the king of the given color is in check."""
        king_pos = board.find_king(color)
        if king_pos is None:
            return False
        enemy = 'b' if color == 'w' else 'w'
        return self.is_square_attacked(board, king_pos[0], king_pos[1], enemy)

    def get_legal_moves(self, game_state) -> list[Move]:
        """Generate all fully legal moves for the current position.

        A move is legal if:
        1. It is pseudo-legal (generated by MoveGenerator)
        2. After making the move, the moving side's king is NOT in check
        """
        pseudo_legal_moves = self.move_generator.generate_moves(game_state)
        legal_moves = []
        color = game_state.turn

        for move in pseudo_legal_moves:
            # Make the move on a copy of the game state
            gs_copy = game_state.copy()
            gs_copy.make_move_no_validate(move)
            # Check if our king is in check after the move
            if not self.is_in_check(gs_copy.board, color):
                legal_moves.append(move)

        return legal_moves

    def is_checkmate(self, game_state) -> bool:
        """Return True if the current side to move is in checkmate."""
        if not self.is_in_check(game_state.board, game_state.turn):
            return False
        return len(self.get_legal_moves(game_state)) == 0

    def is_stalemate(self, game_state) -> bool:
        """Return True if the current side to move is in stalemate."""
        if self.is_in_check(game_state.board, game_state.turn):
            return False
        return len(self.get_legal_moves(game_state)) == 0
